{% set name = "tsam" %}
{% set version = "2.3.9" %}
{% set python_min = "3.9" %}
{% set python_max = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsam-{{ version }}.tar.gz
  sha256: 1f219eef05788d199af1ff61bd5a3d9217a26f9279988b1ef4b7d5af2757ed15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - pip
  run:
    - python >={{ python_min }},<={{ python_max }}
    - scikit-learn >=0.0
    - pandas >2.0.3
    - numpy >=1.20
    - pyomo >=6.4.3
    - networkx
    - tqdm
    - highspy

test:
  imports:
    - tsam
  source_files:
    - .
  commands:
    - pytest -n auto test/
    - pip check
  requires:
    - pip
    - pytest-xdist
    - python {{ python_min }}

about:
  home: https://github.com/FZJ-IEK3-VSA/tsam
  summary: Time series aggregation module (tsam) to create typical periods
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://tsam.readthedocs.io/en/master/
  dev_url: https://github.com/FZJ-IEK3-VSA/tsam


extra:
  recipe-maintainers:
    - maximilian-hoffmann
    - julian-belina
