{% set name = "tsam" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsam-{{ version }}.tar.gz
  sha256: d904004b812a84a0bb4dbb8c7bd4fddb8bc584b526a21664fe475ca3b4db2f5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
    - setuptools-git
  run:
    - networkx
    - numpy >=1.11.0
    - pandas >=0.18.1
    - pyomo >=5.3
    - python >=3.0
    - scikit-learn >=0.0
    - tqdm
    - highspy

test:
  imports:
    - tsam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FZJ-IEK3-VSA/tsam
  summary: Time series aggregation module (tsam) to create typical periods
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://tsam.readthedocs.io/en/master/
  dev_url: https://github.com/FZJ-IEK3-VSA/tsam


extra:
  recipe-maintainers:
    - OfficialCodexplosive
    - maximilian-hoffmann
    - julian-belina
