{% set name = "tsam" %}
{% set version = "3.0.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsam-{{ version }}.tar.gz
  sha256: 8574f045f28a06340cbc3a7909f3fb023c88ed996fcb2593b058b9f88830186f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.0
    - pip
  run:
    - python >={{ python_min }},<={{ python_max }}
    - scikit-learn >=1.3.0,<=1.8.0
    - pandas >=2.2.0,<=3.0.0
    - numpy >=1.22.4,<=2.4.1
    - pyomo >=6.4.3,<=6.95
    - networkx >=2.5,<=3.6.1
    - tqdm >=4.21.0,<=4.67.1
    - highspy >=1.7.2,<=1.12.0
    - plotly >=5.0.0
    - matplotlib

test:
  imports:
    - tsam
  source_files:
    - .
  commands:
    - pytest -n auto test/
    - pip check
  requires:
    - pip
    - pytest-xdist
    - python {{ python_min }}

about:
  home: https://github.com/FZJ-IEK3-VSA/tsam
  summary: Time series aggregation module (tsam) to create typical periods
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://tsam.readthedocs.io/en/master/
  dev_url: https://github.com/FZJ-IEK3-VSA/tsam


extra:
  recipe-maintainers:
    - maximilian-hoffmann
    - julian-belina
