{% set name = "tsam" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsam-{{ version }}.tar.gz
  sha256: f2f75cbcd5d5d63d9d77ec5edb61e7efeb3170ebef4591272ef13a7bd84cc9d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools >=64.0.0
    - pip
  run:
    - python >=3.9,<3.13
    - scikit-learn >=0.0
    - pandas >2.0.3
    - numpy >=1.20
    - pyomo >=6.4.3
    - networkx
    - tqdm
    - highspy

test:
  imports:
    - tsam
  source_files:
    - .
  commands:
    - pytest -n auto test/
    - pip check
  requires:
    - pip
    - pytest-xdist

about:
  home: https://github.com/FZJ-IEK3-VSA/tsam
  summary: Time series aggregation module (tsam) to create typical periods
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://tsam.readthedocs.io/en/master/
  dev_url: https://github.com/FZJ-IEK3-VSA/tsam


extra:
  recipe-maintainers:
    - OfficialCodexplosive
    - maximilian-hoffmann
    - julian-belina
