context:
  version: "3.3.0"
  python_min: "3.10"
  python_max: "3.14.3"

package:
  name: tsam
  version: ${{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/tsam/archive/v${{ version }}.tar.gz
  sha256: 79adc4aa9bfc75de5ff824b0f9f000e0c9f631114f86f917a3e6ebe404d22fe6

build:
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }},<=${{ python_max }}
    - scikit-learn >=1.3.0,<=1.8.0
    - pandas >=2.2.0,<=3.0.1
    - numpy >=1.22.4,<=2.4.3
    - pyomo >=6.4.3,<=6.10.0
    - networkx >=2.5,<=3.6.1
    - tqdm >=4.21.0,<=4.67.3
    - highspy >=1.7.2,<=1.13.1
    - plotly >=5.0.0,<=6.6.0

tests:
  - script:
      - pytest -n auto -vvv
    requirements:
      run:
        - pytest <=9.0.2
        - pytest-cov <=7.1.0
        - pytest-xdist <=3.8.0
        - python ${{ python_min }}.*
    files:
      source:
        - test/
        - docs/notebooks/
        - pyproject.toml
about:
  homepage: https://github.com/FZJ-IEK3-VSA/tsam
  summary: Time series aggregation module (tsam) to create typical periods
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - julian-belina
